name: Deploy to EC2

on:
  push:
    branches:
      - main   # or the branch you want to trigger deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./ ${{
          secrets.EC2_USER
        }}@${{ secrets.EC2_IP }}:/home/${{ secrets.EC2_USER }}/app

    - name: Run setup and start app on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}/app
          npm install
          pm2 delete app || true
          pm2 start app.js --name app
        EOF
